package extractor;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.net.MalformedURLException;

/**
 * @author Uri
 */

// https://api.binance.com/api/v1/klines?symbol=BTCUSDT&interval=1m&startTime=1577833200000&limit=1000

public class Main {
    
    public static String propertiesFilePath = "/Users/Uri/NetBeansProjects/DataBot/src/BTCUSDT/DataProperties.txt";
    public static int year;
    

    public static void main(String[] args) throws MalformedURLException, IOException, Exception {

        writeFile1();
        test();
    }
    
    public static void test() throws IOException, FileNotFoundException, ClassNotFoundException {
        
        ExtractionProperties properties = new ExtractionProperties(2020, propertiesFilePath);
        ExtractionProcess process = new ExtractionProcess(properties);
        process.startExtraction(0, 0);
    }
    
    public static void writeFile1() throws IOException {
        
	File fout = new File(propertiesFilePath);
	FileOutputStream fos = new FileOutputStream(fout);
 
	BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fos));
 
	
	bw.write("https://api.binance.com/api/v1/klines?symbol=BTCUSDT&interval=1m");
	bw.newLine();
        bw.write("/Users/Uri/NetBeansProjects/DataBot/src/BTCUSDT");
        bw.newLine();
        bw.write("AG2017");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("SP2017");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("OC2017");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("NV2017");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("DC2017");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        
        bw.write("JA2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("FB2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("MR2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("AP2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("MY2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("JN2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("JY2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("AG2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("SP2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("OC2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("NV2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("DC2018");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        
        bw.write("JA2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("FB2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("MR2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("AP2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("MY2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("JN2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("JY2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("AG2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("SP2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("OC2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("NV2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("DC2019");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        
        bw.write("JA2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("FB2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("MR2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("AP2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("MY2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("JN2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("JY2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("AG2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("SP2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("OC2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("NV2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("DC2020");
        bw.newLine();
        bw.write("0");
        bw.newLine();
        bw.write("null");
        bw.newLine();
        bw.write("null");
        
	bw.close();
    }
}
